#!/bin/bash
echo "FPKG v0.1-r1"
sleep 1
echo " "
read -rp "Select a option' [i/r/h]: " response
case "$response" in
	[h] )
		echo "FRUE Package Kit Getter"
		sleep 0.5
		echo "Version 0.1-r1"
		sleep 1
		echo " "
		echo "Options: [i/r/h]"
		echo " "
		echo "i - installs a package"
		echo "r - removes a package"
		echo "h - displays this help dialog"
		sleep 1
		;;
	[i] )
		read -rp "What package you wanna install? " pkgname
				sleep 1
				echo " :: Searchin' for package ..."
				sleep 3
				echo " !! Package finded!"
				sleep 0.5
				echo " These packages gon be INSTALLED: "
				echo "======PKG==============VERSION============REPO========"
				echo "$pkgname.fpkg          0.1-r1   Suppabreak/FRUE-Games"
				echo "======================================================"
				read -rp "Cop packages n' install? [y/n]: " reply
				case "$reply" in
					[nN])
						echo " !! Didn't do jack shit..."
						;;

					[yY])
						echo " :: Downloadin' packages..."
						cd /tmp
						git clone https://github.com/Suppabreak/FRUE-Games > /dev/null 2>&1
						rm /tmp/FRUE-Games/LICENSE
						rm /tmp/FRUE-Games/README.md
						echo " :: Unpackin' executables..."
						mv /tmp/FRUE-Games/tic-tac-frue /usr/bin
						sleep 2
						echo " :: Fixin' executables..."
						chmod +x /usr/bin/tic-tac-frue
						sleep 1
						echo " :: Cleanin' up..."
						echo " !! Done!!1 :)"
						sleep 1
						;;
				esac
		;;
	[r] ) 
		read -rp "What package you wanna get rid of? " pkgname
				echo " :: Lookin' in /usr/bin ..."
				sleep 1
				echo " !! Packages finded!"
				sleep 0.5
				echo "These packages gon be DELETED:"
				echo "======PKG=============VERSION============REPO========"
				echo "$pkgname           0.1-r1          /usr/bin"
				echo "====================================================="
				read -rp "Are you sure you wanna get rid of these packages? [y/n]: " yesno
				case "$yesno" in
					[nN])
						echo " !! Didn't do jack shit..."
						;;
					[yY])
						echo " !! Removing in 3..."
						sleep 1
						echo " !! Removing in 2..."
						sleep 1
						echo " !! Removing in 1..."
						sleep 1
						if [[ -d /usr/bin/"$pkgname" ]]; then
							rm /usr/bin/"$pkgname"
						elif [[ -f /usr/bin/"$pkgname" ]]; then
							rm /usr/bin/"$pkgname"
						else
							echo " !! Error !! How 'bout yue install that package first?"
							exit 1
						fi
						echo "Packages removed!!1 :)"
						sleep 1
						;;
				esac
		esac
exit
